CREATE TABLE alerts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    packet_id   BIGINT                                  NOT NULL,
    alert_type  VARCHAR(50)                             NOT NULL,
    severity    VARCHAR(20)                             NOT NULL,
    message     TEXT,
    status      VARCHAR(20)                             NOT NULL,
    resolved_by BIGINT,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_alerts PRIMARY KEY (id)
);

CREATE TABLE packets
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_ip   VARCHAR(45)                             NOT NULL,
    dest_ip     VARCHAR(45)                             NOT NULL,
    protocol    VARCHAR(10)                             NOT NULL,
    size        INTEGER                                 NOT NULL,
    label       VARCHAR(100)                            NOT NULL,
    attack_type VARCHAR(50)                             NOT NULL,
    confidence  DOUBLE PRECISION                        NOT NULL,
    captured_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    timestamp   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_packets PRIMARY KEY (id)
);

CREATE TABLE reports
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(100)                            NOT NULL,
    content      TEXT,
    generated_by BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_reports PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(50)                             NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE alerts
    ADD CONSTRAINT FK_ALERTS_ON_PACKET FOREIGN KEY (packet_id) REFERENCES packets (id);

ALTER TABLE alerts
    ADD CONSTRAINT FK_ALERTS_ON_RESOLVED_BY FOREIGN KEY (resolved_by) REFERENCES users (id);

ALTER TABLE reports
    ADD CONSTRAINT FK_REPORTS_ON_GENERATED_BY FOREIGN KEY (generated_by) REFERENCES users (id);